require: rubocop-rspec

#
# This file is called via the .rubocop.yml "inherit_from: config/rubocop.yml"
#
AllCops:
  UseCache: true
  MaxFilesInCache: 4000

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  # added 0.82
  Enabled: true

Layout/LineLength:
  Max: 130

Layout/EmptyLinesAroundAttributeAccessor:
  # added  (0.83)
  Enabled: true

Lint:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  # added (0.89)
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
# added  (0.84)
  Enabled: false
Lint/DuplicateElsifCondition:
# added  (0.88)
  Enabled: true
Lint/DuplicateRescueException:
# added  (0.89)
  Enabled: true
Lint/EmptyConditionalBody:
# added  (0.89)
  Enabled: true
Lint/FloatComparison:
# added  (0.89)
  Enabled: false
Lint/MissingSuper:
# added  (0.89)
  Enabled: true
Lint/MixedRegexpCaptureTypes:
# added  (0.85)
  Enabled: false
Lint/OutOfRangeRegexpRef:
# added  (0.89)
  Enabled: false
Lint/SelfAssignment:
# added  (0.89)
  Enabled: false
Lint/TopLevelReturnWithArgument:
# added  (0.89)
  Enabled: true
Lint/UnreachableLoop:
# added  (0.89)
  Enabled: true

Lint/RaiseException:
  # added 0.81
  Enabled: true

Lint/StructNewOverride:
  # added 0.81
  Enabled: true
Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true
Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true
Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true
Lint/EmptyFile: # (new in 0.90)
  Enabled: true
Lint/IdentityComparison: # (new in 0.91)
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true
Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true
Lint/UselessTimes: # (new in 0.91)
  Enabled: true

Metrics:
  Enabled: false

Naming:
  Enabled: true

Rails:
  Enabled: true
Rails/ApplicationRecord:
  Enabled: true
Rails/InverseOf:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: true
  # Could not figure out how to replace where: where(['lower(account_name) = :value', conditions]).first
Rails/FindBy:
  Enabled: false
Rails/Date:
  Enabled: true
Rails/Validation:
  Enabled: true
Rails/HttpPositionalArguments:
  Enabled: true
Rails/BulkChangeTable:
  Exclude:
    # not run anymore
    - './db/migrate/20180209181803_add_column_first_comm_at_stmm.rb'
    - './db/migrate/20180209181803_add_column_first_comm_at_stmm.rb'

Rails/ActiveRecordCallbacksOrder:
# added  (2.7)
  Enabled: false
Rails/FindById:
# added  (2.7)
  Enabled: true
Rails/Inquiry:
# added (2.7)
  Enabled: true
Rails/MailerName:
# added (2.7)
  Enabled: true
Rails/MatchRoute:
# added (2.7)
  Enabled: true
Rails/NegateInclude:
# added (2.7)
  Enabled: true
Rails/Pluck:
# added (2.7)
  Enabled: true
Rails/PluckInWhere:
# added (2.7)
  Enabled: true
Rails/RenderInline:
# added   (2.7)
  Enabled: true
Rails/RenderPlainText:
# added   (2.7)
  Enabled: true
Rails/ShortI18n:
# added   (2.7)
  Enabled: true
Rails/WhereExists:
# added  (2.7)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: false
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: false
Rails/WhereNot: # (new in 2.8)
  Enabled: false

Security:
  Enabled: true

Style:
  Enabled: true
  # could not figure out how to use with method mail(...) do ...
  # all examples use enumerators like map, each

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    # need to figure out how 'Use nested module/class definitions instead of compact style'
    - './spec/support/devise_rails_5_helpers.rb'

Style/ExponentialNotation:
  # added 0.82
  Enabled: false

Style/HashEachMethods:
  # added 0.80
  Enabled: false

Style/HashTransformKeys:
  # added 0.80
  Enabled: false

Style/HashTransformValues:
  # added 0.80
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    # need to figure out how to make DeviseHelpers & DeviseRails5Helpers available to
    # erb.
    - './spec/views/admins/passwords/new.html.erb_spec.rb'
    - './spec/views/candidates/registrations/new.html.erb_spec.rb'
    - './spec/views/candidates/edit.html.erb_spec.rb'
    - './spec/views/candidates/registrations/edit.html.erb_spec.rb'

# An extension cop that will cause the build to be broken if
# the right documentation is not present.
Style/PublicMethodDocumentation:
  Enabled: true

Style/PublicClassDocumentation:
  Enabled: true

# this added to allow tests to work
Style/CommentAnnotation:
  Keywords: []
  Enabled: false

Style/SymbolArray:
  Enabled: true
  Exclude:
    # does not work well with require/permit 'Use %i or %I for an array of symbols'
    - './app/controllers/common_candidates_controller.rb'

Style/SymbolProc:
  Enabled: true
  Exclude:
    - './app/models/candidates_mailer.rb'


Style/AccessorGrouping:
# added   (0.87)
  Enabled: true
Style/ArrayCoercion:
# added   (0.88)
  Enabled: true
Style/BisectedAttrAccessor:
# added   (0.87)
  Enabled: false
Style/CaseLikeIf:
# added   (0.88)
  Enabled: true
Style/ExplicitBlockArgument:
# added   (0.89)
  Enabled: true
Style/GlobalStdStream:
# added   (0.89)
  Enabled: true
Style/HashAsLastArrayItem:
# added   (0.88)
  Enabled: true
Style/HashLikeCase:
# added   (0.88)
  Enabled: true
Style/OptionalBooleanParameter:
# added   (0.89)
  Enabled: true
Style/RedundantAssignment:
# added   (0.87)
  Enabled: true
Style/RedundantFetchBlock:
# added   (0.86)
  Enabled: true
Style/RedundantFileExtensionInRequire:
# added   (0.88)
  Enabled: true
Style/RedundantRegexpCharacterClass:
# added   (0.85)
  Enabled: true
Style/RedundantRegexpEscape:
# added   (0.85)
  Enabled: true
Style/SingleArgumentDig:
# added   (0.89)
  Enabled: true
Style/SlicingWithRange:
# added   (0.83)
  Enabled: true
Style/StringConcatenation:
  # added  (0.89)
  Enabled: true
Style/CombinableLoops: # (new in 0.90)
  Enabled: true
Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true
Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true
Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true


#AllCops:
#  NewCops: enable


Gemspec/DeprecatedAttributeAssignment: # new in 1.10
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
Lint/ToEnumArguments: # new in 1.1
  Enabled: false
Lint/TripleQuotes: # new in 1.9
  Enabled: false
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: false
Naming/InclusiveLanguage: # new in 1.18
  Enabled: false
Style/ArgumentsForwarding: # new in 1.1
  Enabled: false
Style/CollectionCompact: # new in 1.2
  Enabled: false
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: false
Style/EndlessMethod: # new in 1.8
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/HashExcept: # new in 1.7
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Rails/WhereEquals: # new in 2.9
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never
  Enabled: true

Gemspec/RequireMFA: # new in 1.23
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true
Naming/BlockForwarding: # new in 1.24
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/FileRead: # new in 1.24
  Enabled: true
Style/FileWrite: # new in 1.24
  Enabled: true
Style/MagicCommentFormat: # new in 1.35
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Style/MapToHash: # new in 1.24
  Enabled: true
Style/NestedFileDirname: # new in 1.26
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true

RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11.0
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: false
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/Capybara/SpecificMatcher: # new in 2.12
  Enabled: false
RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: false
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: false
RSpec/NestedGroups: # new in 2.12
  Enabled: false